apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightly-performance
spec:
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: network
              configMap:
                name: network
          containers:
            - name: nightly-performance
              volumeMounts:
                - name: network
                  mountPath: /network
