---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: keramik-ssd
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-ssd
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer