---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nightly-performance-recon-event-sync-20m
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nightly-performance
subjects:
  - kind: ServiceAccount
    name: nightly-performance