apiVersion: batch/v1
kind: Job
metadata:
  name: ceramic-new-streams-1w!!!TEMPLATE!!!
  namespace: ceramic-new-streams-1w
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - bash
            - /config/nightly-performance.sh
          env:
            - name: JOB_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: DISCORD_WEBHOOK_URL_SUCCEEDED
              valueFrom:
                secretKeyRef:
                  key: DISCORD_WEBHOOK_URL_SUCCEEDED
                  name: discord
            - name: DISCORD_WEBHOOK_URL_FAILED
              valueFrom:
                secretKeyRef:
                  key: DISCORD_WEBHOOK_URL_FAILED
                  name: discord
          envFrom:
            - configMapRef:
                name: local-config-b7mbtf65m4
          image: google/cloud-sdk
          imagePullPolicy: Always
          name: nightly-performance
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /network
              name: network
            - mountPath: /simulation
              name: simulation
            - mountPath: /config
              name: nightly-performance
            - mountPath: /notifications
              name: notifications
            - mountPath: /scripts
              name: scripts
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nightly-performance
      serviceAccountName: nightly-performance
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: network-k59dbk49b9
          name: network
        - configMap:
            defaultMode: 420
            name: simulation-8dh29m69g9
          name: simulation
        - configMap:
            defaultMode: 420
            name: nightly-performance-7t6t4f6bm5
          name: nightly-performance
        - configMap:
            defaultMode: 420
            name: notifications-57k62bc7g5
          name: notifications
        - configMap:
            defaultMode: 420
            name: scripts-5hcmc4598g
          name: scripts
