---
apiVersion: "keramik.3box.io/v1alpha1"
kind: Network
metadata:
  name: nightly-dev-hermetic
spec:
  replicas: 2
  ttlSeconds: 14400
  ceramic:
    - resourceLimits:
        cpu: "4"
        memory: 4Gi
      ipfs:
        rust:
          env:
            RUST_LOG: info,recon=trace
            CERAMIC_ONE_LOG_FORMAT: "json"
            SQLITE_TMPDIR: ":memory:"
          resourceLimits:
            cpu: "4"
            memory: 4Gi
            storage: 10Gi
          image: public.ecr.aws/r5b3e0r5/3box/ceramic-one:sync-id
          storageClass: keramik-ssd
  # Use Kubo with CAS because it still needs pubsub
  cas:
    ipfs:
      go: {}
  monitoring:
    namespaced: true